version: "3.7"
services:
  web:
    build:
      context: ./docker
      target: dev
    stdin_open: true
    tty: true
    command: bundle exec hanami server --host=0.0.0.0
    volumes:
      - ".:/dbt_assistant"
      - bundle:/bundle
    ports:
      - "2300:2300"
    depends_on:
      - db

  db:
    image: "healthcheck/postgres:alpine"
    environment:
      POSTGRES_PASSWORD: db_password

volumes:
  bundle: